Repository platy-org/pdum-genome, pull requests merged in 2025-02, with the labels that each got.

#47 Annotate smoothened
  chunks/scaffold_9.gff3-00
Labels: naming

#46 Annotate FzCRD-3
  chunks/scaffold_15.gff3
Labels: naming

#45 Annotate FzCRD-2
  chunks/scaffold_3.gff3-02
Labels: naming

#44 Annotate FzCRD-1
  chunks/unplaced.gff3-03
Labels: naming

#43 Annotate sFRP-3/4
  chunks/scaffold_10.gff3-01
Labels: naming

#42 Annotate sFRP-1/2/5
  chunks/scaffold_10.gff3-00
Labels: naming

#41 Annotate Frizzled-9/10
  chunks/scaffold_1.gff3-09
Labels: naming

#38 Annotate Frizzled-5/8
  chunks/scaffold_12.gff3-00
Labels: naming

#35 Annotate arrowhead
  chunks/scaffold_6.gff3-01
Labels: naming

#34 Annotation: Ras-GTPase-activating protein-binding-like protein
  chunks/scaffold_2.gff3-04
Labels: good first issue, naming

#33 PR template for gene name proposals
  docs/PULL_REQUEST_TEMPLATE/gene_name.md
Labels: documentation, enhancement, help wanted

#30 annotate foxA
  chunks/scaffold_7.gff3-01
Labels: naming

#25 annotate tektin4
  chunks/scaffold_10.gff3-00
Labels: naming

#24 annotate tektin3/5b
  chunks/scaffold_10.gff3-02
Labels: naming

#21 annotate tektin2
  chunks/scaffold_1.gff3-03
Labels: naming

#20 annotate wnt2
  chunks/scaffold_7.gff3-01
Labels: naming

#18 Annotation: dbh (dopamine beta-hydroxylase)
  chunks/scaffold_6.gff3-01
Labels: naming

#14 Update scaffold_29.gff3
  chunks/scaffold_29.gff3
Labels: naming

#13 annotate FMRFamide
  chunks/scaffold_10.gff3-01
  chunks/scaffold_14.gff3
Labels: naming

#12 Update scaffold_2.gff3-05
  chunks/scaffold_2.gff3-05
Labels: naming

#10 Update scaffold_4.gff3-03 MIP/allatostatin B receptor
  chunks/scaffold_4.gff3-03
Labels: naming

#9 annotate myoinhibitory peptide
  chunks/unplaced.gff3-05
Labels: naming

#7 Update scaffold_1.gff3-06
  chunks/scaffold_1.gff3-06
Labels: naming

#5 annotate hes2
  chunks/scaffold_17.gff3
Labels: naming

#4 annotate hes1
  chunks/scaffold_2.gff3-04
Labels: naming
